### ISSUE TITLE
API (allow other scripts to access the clipboard history)

### ISSUE THREAD

**Issue by hi5** [hi5/CL3#11]
Using [ObjRegisterActive](https://autohotkey.com/boards/viewtopic.php?f=6&t=6148)

APIs:
- [x] search
- [x] set/update
- [x] insert
- [x] delete
- [x] Burst
- [x] Search (return text); Search (return Index)
- [x] FIFO: turn on/off
- [x] Current ClipChain data
- [x] Current Slots data
- [x] Upper, lower, title

Other resources: 
* GuiVar seems to be a nice/easier alternative https://autohotkey.com/boards/viewtopic.php?p=254641#p254641
* Use [OnMessage](https://autohotkey.com/docs/commands/OnMessage.htm)
* Using [talk()](https://github.com/aviaryan/autohotkey-scripts/blob/master/Functions/talk.ahk) might be easier as we need two way communication to and from CL3 ?

**Comment by joedf** [comment]
Great! :+1:

**Comment by hi5** [comment]
Practically ready - todo:

- [ ] testing, test scripts
- [ ]  documentation

**Comment by hi5** [comment]
Added API in v1.94 using ObjRegisterActive - surprisingly easy.
