### ISSUE TITLE
Exclude certain programs

### ISSUE THREAD

**Issue by tanrak** [hi5/CL3#16]
Hi, first of all thank you for this good piece of software, especially the possibility of cycle through clipboard.
You have on the todo the point "Exclude certain programs". Is that still up to date? I am mainly thinking at various password tools. It would be good for privacy if this software could ignore the windows of KeePass, for example.

**Comment by hi5** [comment]
Wasn't planning too but can be useful of course.

You can try https://github.com/hi5/CL3/tree/v1.99 - add a list of program.exe in csv format "program1.exe,keepass.exe" etc in the settings.

If the current clipboard is changed by one of the excluded programs and you popup the menu it shows "a*" in the first entry indicating the current clipboard has a different content as to what is shown in the menu.

Backup your current CL3, as I only briefly tested it.

**Comment by tanrak** [comment]
Wonderful! It seems to work as expected but the entry must be case sensitive. For example the entry must be "KeePass.exe" for the  software KeePass. Thanks for this fast commit.

**Comment by hi5** [comment]
Cheers, I'll make it case insensitive in the next update.

**Comment by hi5** [comment]
Now in v1.99

**Comment by hi5** [comment]
Update Gui for settings in v1.99.1 repo, somehow it wasn't uploaded in v.199

**Comment by tanrak** [comment]
I had seen that. In the lower right corner. Thanks again for the integration.
