### ISSUE TITLE
Feature request: Activate/access normal hotkey menu via right-click context menu

### ISSUE THREAD

**Issue by u0i299pg** [hi5/CL3#17]
If possible, and if not too complex a task, would it be possible to add an entry to the right-click context menu that would invoke the main CL3 menu that displays when pressing the "#v" hotkey? 

On a somewhat related note, I've noticed the clipboard history accessed via the main "#v" hotkey to be significantly shorter than the list accessed when opening the "Search" interface. I have been finding myself defaulting to the "Search" interface for this reason. Is there a way to enable accessing the full clipboard history using the "#v" hotkey? Perhaps a checkbox or max-#-of-entries field could be added to the Settings?

**Comment by hi5** [comment]
1. I don't think there is a reliable way to modify the context menu of all programs, but you could add a hotkey (say Winkey-Rbutton or Lbutton, on line 186 https://github.com/hi5/CL3/blob/master/cl3.ahk#L186 add
`#Rbutton::` or `#Lbutton::` restart CL3 and you should be able to press that shortcut to show the menu.

2. You can try changing 18 to a higher number, say 40 on line 408 https://github.com/hi5/CL3/blob/master/cl3.ahk#L408 `If (A_Index = 40) ; was 18` but now you have to press t twice to get to templates for example - I choose 18 to have s for special and t for templates available.

**Comment by hi5** [comment]
Or change `43` to say `100` in https://github.com/hi5/CL3/blob/master/cl3.ahk#L520 to give you more as 26 entries in the "more history" secondary menu. That is something I may add as config.

**Comment by hi5** [comment]
In v1.100 https://github.com/hi5/CL3 you can now

* New setting: **number of entries in "z. More history"** (default 26 for a to z), repeating menu accelerators. Use a negative value e.g. -30 to avoid repeating menu accelerators.
* New setting: **second Show Menu hotkey** to be able to define mouse button for example (Winkey+LButton).
* If there are over 26 templates in a folder, repeating menu accelerators (a-z).
* New: Check if a sub-folder in \templates\ has a "settings.ini" with a "shortcut" key, if so, setup hotkey to show sub-templates menu directly by passing the main menu, templates, folder navigation.
* Now using CRC32 to avoid duplicate entries, hopefully faster and more efficient.
* Fix: Compact(ing) adding lines and crc to compacted history as well.
