### ISSUE TITLE
Retain the histroy to only 6 slots

### ISSUE THREAD

**Issue by yasinULLAH** [hi5/CL3#18]
I have retain the history to only slots (max histroy: 6; menu width: 1; more histroy: 0). but the CL3 history still goes up to "Z" I wanted it to start from beginning when it is reached 6 "G" even though the rest of all slots are showing empty but I am still been cycled up to to the z slot.

**Comment by hi5** [comment]
Yes, it doesn't take such low(er) maxresults into account yet - so you to cycle from `a` to `f` and when you cycle again go back to `a` like so (I moved the mouse in the past part but it goes from `f` to `a`
![2cycle](https://user-images.githubusercontent.com/1973899/198647143-920905f9-deb8-4b2b-84a4-12032ba6577b.gif)

Do you want to be able to determine which parts of the menu (what you see when you press ctrl-alt-v) are show as well?
For example don't show the `templates` or `special` menu options?

**Comment by yasinULLAH** [comment]
Sir pardon me but I didn't understand what meant by this comment. Please simply answer me that if it is possible or not if so than tell the way how to do it. If not than please add this feature it will very much appreciated.

**Comment by hi5** [comment]
Hello - I'm trying to understand the request you are making so I made a demonstration animation (the image above) as shown above.

Does the image show what you want it to do? If so can try to add that to CL3.

**Comment by yasinULLAH** [comment]
yes sir the exactly wanted whatever is shown in that image

**Comment by hi5** [comment]
If all went well this is now added to [v1.103](https://github.com/hi5/CL3/archive/refs/heads/master.zip) .
You can also show/hide elements of the main CL3 menu (Special, Templates, Yank, More history, and Exit)

**Comment by yasinULLAH** [comment]
Excellent work Sir, Bundle Of thanks

now the only and last thing needed is the **standalone portable exe version** of this app which update itself

**Comment by yasinULLAH** [comment]
Excellent work Sir, Bundle Of thanks

now the only and last thing needed is the **standalone portable exe version** of this app which update itself
