### ISSUE TITLE
Compiled version for each release w update option?

### ISSUE THREAD

**Issue by hi5** [hi5/CL3#19]
> now the only and last thing needed is the **standalone portable exe version** of this app which update itself -- [link](https://github.com/hi5/CL3/issues/18#issuecomment-1296502546)

Not sure if there is an interest in a compiled version of CL3? If so comment below.

**Comment by yasinULLAH** [comment]
Sir I have recommended this app to my whole company wanted it to grow more because this is the best utility there is but the problem is that no one has installed AHK in their system. so that's why please make portable and in one file if you could and make it auto updatable

**Comment by yasinULLAH** [comment]
Two Main issues

1. sir there is error with loading of that icon "Error: can't load icon". res\cl3.ico
so I tried and added a random icon to the "res" folder with the name cl3.ico and it started working fine. 

2. I already noticed this error when I compiled the ahk earlier myself but to try it I uninstalled AHK from my computer. and the than try to load the cl3.exe utility and it immediately stopped working. so without AHK installed this won't work. Please fix these two issues ♥ .

To see these error for yourself please try it on another system without having AHK installed on that system...

**Comment by hi5** [comment]
That is why I don't like compiling. Should be fixed now https://github.com/hi5/CL3/releases/tag/v1.105

**Comment by yasinULLAH** [comment]
me too sir but the reason is that we can't tell to install ahk just for this app. so everybody likes a standalone app. anyways bundle of thanks for ur concern will check it on my personal computer night time inshallah

**Comment by yasinULLAH** [comment]
Just checked it on my Laptop the icon problem is fixed but the AHK problem is still intact means if we don't have AHK installed it won't work.

**Comment by yasinULLAH** [comment]
I Don't know what the problem is but I have tried everything disabled my antivirus etc. still wasn't working but as soon as i installed AHK on that system it started working.

**Comment by hi5** [comment]
All I can think of is that perhaps the [Windows clipboard history](https://www.howtogeek.com/351978/using-windows-10s-new-clipboard-history-and-cloud-sync/) is active?

**Comment by yasinULLAH** [comment]
the error is related to file which is not found in the ahk folder of C drive

**Comment by hi5** [comment]
> the error is related to file which is not found in the ahk folder of C drive

That helps - again to do with the icons, should be fixed now in https://github.com/hi5/CL3/releases/tag/v1.106

**Comment by yasinULLAH** [comment]
Awesome Excellent Sir Working Fine Now Even Without installing AHK 🤩🤩

**Comment by hi5** [comment]
perfect
