### ISSUE TITLE
Date/time inclusion in History.xml

### ISSUE THREAD

**Issue by J-L-Taylor** [hi5/CL3#23]
If doing so would not cause adverse effects, adding a time entry to the History.xml file would be convenient to have included with the existing entries. For example,
```
<History>
	<Invalid_Name id="1" ahk="True">
		<crc>…</crc>
		<icon>…</icon>
		<lines>…</lines>
		<time>…</time>
		<text>Thank you for CL3!</text>
	</Invalid_Name>
```
I would open a pull request, but I tried to get an understanding of the variables used in CL3.ahk and was unsuccessful…

**Comment by hi5** [comment]
Adding new entries to the history is done using the [.InsertAt ](https://www.autohotkey.com/docs/v1/lib/Object.htm#InsertAt) done here https://github.com/hi5/CL3/blob/74a75a77fed2de5da14dd8aa7bfbc3f95fa39b21/cl3.ahk#L818
(and in a few other places) and updating entries simply manipulates the index value of the history object.

So adding time could probably be as easy as adding `,"Time":A_Now`

```autohotkey
History.Insert(1,{"text":ClipText,"icon": IconExe,"lines": Count+1,"crc":crc,"Time":A_Now})
```

Of course that doesn't do much good as the user can't see it, so what would you do with it? 
Do you want to display it in the menu, cycle through history or search results?

**Comment by J-L-Taylor** [comment]
Having the time displayed in any of the places you mentioned would be
quite helpful, though I imagine it would be most useful in the search
results as it may help the user find what they're looking for if they can
view the times of the entries as they scroll through the list.

**Comment by hi5** [comment]
I'll do some tests and see if I can incorporate it somehow (at some point)

**Comment by hi5** [comment]
You can try [v1.107](https://github.com/hi5/CL3/archive/refs/heads/master.zip) and set it up via the settings https://github.com/hi5/CL3/blob/master/changelog.md#v1107
I haven't tested it very thoroughly so let me know if you spot something peculiar.

**Comment by hi5** [comment]
Various additions to timestamp in v1.108 which is now also visible in tooltip (cycle forward, backward, plugin) and search.
https://github.com/hi5/CL3/blob/master/changelog.md#v1108
